#cloud-config
datasource:
  Ec2:
    strict_id: false
ssh_pwauth: no
users:
- name: 'vm_user'
  sudo: 'ALL=(ALL) NOPASSWD:ALL'
  shell: /bin/bash
  ssh_authorized_keys:
  - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIACHzbsALfp1KSlI9kt1kvEqkKTs/FqlKCAW4rRuOqv4 sergey@sergey-devops'
